server:
  port: 8080

---
spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8088/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://localhost:8081
          predicates:
            - Path=/pay/**
        - id: gate
          uri: http://localhost:8082
          predicates:
            - Path=/gate/**
        - id: space
          uri: http://localhost:8083
          predicates:
            - Path=/space/**
        - id: keeper
          uri: http://localhost:8084
          predicates:
            - Path=/keeper/**
        - id: state
          uri: http://localhost:8085
          predicates:
            - Path=/state/**
        - id: oauth
          uri: http://localhost:8090
          predicates:
            - Path=/oauth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/pay/**
        - id: gate
          uri: http://gate:8080
          predicates:
            - Path=/gate/**
        - id: space
          uri: http://space:8080
          predicates:
            - Path=/space/**
        - id: keeper
          uri: http://keeper:8080
          predicates:
            - Path=/keeper/**
        - id: state
          uri: http://state:8080
          predicates:
            - Path=/state/**
        - id: oauth
          uri: http://oauth:8080
          predicates:
            - Path=/oauth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080